# -*- coding: utf-8 -*-
"""stock_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9lmDV-lWeU6cdJlFWN8R3EG8wbwj3Hc
"""

import yfinance as yf
import pandas as pd

def get_recent_closing_prices(ticker, count=2500):
    print(f"Fetching last {count} closing prices for {ticker}...")

    # Download 10 years of historical data
    stock_data = yf.download(ticker, period='10y')

    if stock_data.empty:
        return "No data found for the given ticker."

    # Extract the 'Close' column and take the last N entries
    close_prices = stock_data['Close'].tail(count)

    return close_prices

# Define ticker
TICKER_TO_FETCH = 'AAPL'
prices = get_recent_closing_prices(TICKER_TO_FETCH)

if isinstance(prices, pd.Series) or isinstance(prices, pd.DataFrame):
    print(f"\nLast {len(prices)} Closing Prices for {TICKER_TO_FETCH}:")
    display(prices)
else:
    print(prices)

# Calculate the 20-day and 200-day Exponential Moving Averages (EMA)
if isinstance(prices, (pd.Series, pd.DataFrame)):
    # Handle case where prices might be a MultiIndex DataFrame or a Series
    if isinstance(prices, pd.DataFrame) and 'Close' in prices.columns:
        close_data = prices['Close']
    elif isinstance(prices, pd.DataFrame) and isinstance(prices.columns, pd.MultiIndex):
        close_data = prices.xs('Close', axis=1, level=0)
    else:
        close_data = prices

    # Calculate EMAs using ewm
    prices_ema = pd.DataFrame(close_data.copy())
    prices_ema.columns = ['Close']
    prices_ema['20-Day EMA'] = prices_ema['Close'].ewm(span=20, adjust=False).mean()
    prices_ema['200-Day EMA'] = prices_ema['Close'].ewm(span=200, adjust=False).mean()

    # Identify High and Low
    high_price = prices_ema['Close'].max()
    low_price = prices_ema['Close'].min()

    print(f"\nExponential Moving Averages (20/200) for {TICKER_TO_FETCH} (Last 5 days):")
    display(prices_ema.tail(5))
    print(f"Period High: ${high_price:.2f} | Period Low: ${low_price:.2f}")

    # Visualize the results
    import matplotlib.pyplot as plt
    plt.figure(figsize=(14, 7))
    plt.plot(prices_ema.index, prices_ema['Close'], label='Close Price', alpha=0.3, color='gray')
    plt.plot(prices_ema.index, prices_ema['20-Day EMA'], label='20-Day EMA', color='orange', linewidth=2)
    plt.plot(prices_ema.index, prices_ema['200-Day EMA'], label='200-Day EMA', color='red', linewidth=2)

    plt.axhline(y=high_price, color='green', linestyle='--', alpha=0.5, label=f'High (${high_price:.2f})')
    plt.axhline(y=low_price, color='blue', linestyle='--', alpha=0.5, label=f'Low (${low_price:.2f})')

    plt.title(f'{TICKER_TO_FETCH} Trend Analysis: 20/200 EMA & Price Range')
    plt.xlabel('Date')
    plt.ylabel('Price (USD)')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.show()
else:
    print("Error: No price data available.")

# Identify crossover points for 20-Day vs 200-Day EMA
prices_ema['Signal'] = prices_ema['20-Day EMA'] > prices_ema['200-Day EMA']

# Crossover occurs when Signal changes
prices_ema['Crossover_Val'] = prices_ema['Signal'].astype(int).diff()

# Filter for actual crossover events
crossovers_only = prices_ema[prices_ema['Crossover_Val'] != 0].dropna(subset=['Crossover_Val']).copy()

# Label the type of cross
crossovers_only['Type'] = crossovers_only['Crossover_Val'].apply(
    lambda x: 'Golden Cross (Bullish)' if x == 1 else 'Death Cross (Bearish)'
)

if not crossovers_only.empty:
    print(f"20/200 EMA Crossover Events for {TICKER_TO_FETCH}:")
    display(crossovers_only[['Close', '20-Day EMA', '200-Day EMA', 'Type']])
else:
    status = 'above' if prices_ema['Signal'].iloc[-1] else 'below'
    print(f"No 20/200 EMA crossovers detected. The 20-day EMA has remained consistently {status} the 200-day EMA.")


# BUY: If you have no shares and a 'Golden Cross' is active,
# it spends all capital to buy shares at the current price.
# SELL: If you own shares and the price closes below the 20-Day EMA,
# it sells everything to lock in gains or limit losses.
def run_strategy_1(df_ema, initial_capital=100000):
    capital = initial_capital
    shares = 0
    trade_log = []

    # Combine data on index
    combined = pd.DataFrame(index=df_ema.index)
    combined['Close'] = df_ema['Close']
    combined['EMA20'] = df_ema['20-Day EMA']
    combined['Golden_Cross'] = df_ema['20-Day EMA'] > df_ema['200-Day EMA']

    for date, row in combined.iterrows():
        price = row['Close']

        # BUY: Golden Cross
        if shares == 0 and row['Golden_Cross']:
            shares = capital / price
            capital = 0
            trade_log.append({'Date': date, 'Action': 'BUY', 'Price': price, 'Strategy': 'Strategy 1'})

        # SELL: Close below EMA 20
        elif shares > 0 and price < row['EMA20']:
            capital = shares * price
            shares = 0
            trade_log.append({'Date': date, 'Action': 'SELL', 'Price': price, 'Strategy': 'Strategy 1'})

    # Force close at end
    if shares > 0:
        capital = shares * combined['Close'].iloc[-1]
        trade_log.append({'Date': combined.index[-1], 'Action': 'FORCE_SELL', 'Price': combined['Close'].iloc[-1], 'Strategy': 'Strategy 1'})

    return capital, pd.DataFrame(trade_log)

# Run Strategy 1
s1_final, s1_trades = run_strategy_1(prices_ema)

# Add to results table
s1_row = pd.DataFrame({
    'Strategy': ['Strategy 1'],
    'Initial Capital': [100000],
    'Final Value': [s1_final],
    'Total Return (%)': [(s1_final - 100000) / 1000]
})

# Update the summary display
full_results = pd.concat([s1_row], ignore_index=True)
# Format for display
full_results_display = full_results.copy()
full_results_display['Final Value'] = full_results_display['Final Value'].apply(lambda x: f"${x:,.2f}" if isinstance(x, (int, float)) else x)
full_results_display['Total Return (%)'] = full_results_display['Total Return (%)'].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)

print(f"--- Updated Performance including Simplified Strategy 1 ({TICKER_TO_FETCH}) ---")
display(full_results_display)

print("\nStrategy 1 Trade Log (Last 5):")
display(s1_trades.tail(5))

# The Buy Rule: It triggers a purchase when a 'Golden Cross' occurs (20-day EMA crosses above the 200-day EMA)
# if the bot isn't already holding shares.
# The Sell Rule: It triggers a sale if the stock price drops below the 20-day EMA,
# acting as a trend-following trailing exit(fall 5% below the buy price) to protect profits.
def run_strategy_2(df_ema, initial_capital=100000):
    capital = initial_capital
    shares = 0
    buy_price = 0
    trade_log = []

    combined = pd.DataFrame(index=df_ema.index)
    combined['Close'] = df_ema['Close']
    combined['EMA20'] = df_ema['20-Day EMA']
    combined['Golden_Cross'] = df_ema['20-Day EMA'] > df_ema['200-Day EMA']

    for date, row in combined.iterrows():
        price = row['Close']

        # Entry: Golden Cross
        if shares == 0 and row['Golden_Cross']:
            shares = capital / price
            buy_price = price
            capital = 0
            trade_log.append({'Date': date, 'Action': 'BUY', 'Price': price, 'Strategy': 'Strategy 2'})

        elif shares > 0:
            # Condition A: Stop Loss (5% below buy price)
            if price < (buy_price * 0.95):
                capital = shares * price
                shares = 0
                trade_log.append({'Date': date, 'Action': 'STOP_LOSS', 'Price': price, 'Strategy': 'Strategy 2'})

            # Condition B: Close below EMA 20
            elif price < row['EMA20']:
                capital = shares * price
                shares = 0
                trade_log.append({'Date': date, 'Action': 'SELL_EMA20', 'Price': price, 'Strategy': 'Strategy 2'})

    if shares > 0:
        capital = shares * combined['Close'].iloc[-1]
        trade_log.append({'Date': combined.index[-1], 'Action': 'FORCE_SELL', 'Price': combined['Close'].iloc[-1], 'Strategy': 'Strategy 2'})

    return capital, pd.DataFrame(trade_log)

s2_final, s2_trades = run_strategy_2(prices_ema)

s2_row = pd.DataFrame({
    'Strategy': ['Strategy 2'],
    'Initial Capital': [100000],
    'Final Value': [s2_final],
    'Total Return (%)': [(s2_final - 100000) / 1000]
})

final_comparison = pd.concat([full_results, s2_row], ignore_index=True)
final_display = final_comparison.copy()
final_display['Final Value'] = final_display['Final Value'].apply(lambda x: f"${x:,.2f}" if isinstance(x, (int, float)) else x)
final_display['Total Return (%)'] = final_display['Total Return (%)'].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)

print(f"--- Final Comparison with Strategy 2 (Stop-Loss) for {TICKER_TO_FETCH} ---")
display(final_display)
print("\nStrategy 2 Last 5 Trades:")
display(s2_trades.tail(5))

# Buy the stock and hold till today
def run_strategy_3(df, initial_capital=100000):
    # Buy and Hold: Buy on the first day, sell on the last day
    start_price = df['Close'].iloc[0]
    end_price = df['Close'].iloc[-1]
    shares = initial_capital / start_price
    final_value = shares * end_price

    trade_log = pd.DataFrame([
        {'Date': df.index[0], 'Action': 'BUY', 'Price': start_price, 'Strategy': 'Strategy 3'},
        {'Date': df.index[-1], 'Action': 'SELL_END', 'Price': end_price, 'Strategy': 'Strategy 3'}
    ])
    return final_value, trade_log


# Buy when Golden Cross happens and Sell when Death Cross happens
def run_strategy_4(df_crossovers, initial_capital=100000):
    # Strategy 4: Golden Cross (Buy) / Death Cross (Sell)
    capital = initial_capital
    shares = 0
    trade_log = []

    for date, row in df_crossovers.iterrows():
        price = row['Close']
        if row['Type'] == 'Golden Cross (Bullish)' and shares == 0:
            shares = capital / price
            capital = 0
            trade_log.append({'Date': date, 'Action': 'BUY', 'Price': price, 'Strategy': 'Strategy 4'})
        elif row['Type'] == 'Death Cross (Bearish)' and shares > 0:
            capital = shares * price
            shares = 0
            trade_log.append({'Date': date, 'Action': 'SELL', 'Price': price, 'Strategy': 'Strategy 4'})

    if shares > 0:
        capital = shares * df_crossovers['Close'].iloc[-1]
        trade_log.append({'Date': df_crossovers.index[-1], 'Action': 'FORCE_SELL', 'Price': df_crossovers['Close'].iloc[-1], 'Strategy': 'Strategy 4'})

    return capital, pd.DataFrame(trade_log)

# Execute strategies
s3_final, s3_trades = run_strategy_3(prices_ema)
s4_final, s4_trades = run_strategy_4(crossovers_only)

# Create new rows for comparison
new_rows = pd.DataFrame([
    {'Strategy': 'Strategy 3 (B&H)', 'Initial Capital': 100000, 'Final Value': s3_final, 'Total Return (%)': (s3_final - 100000) / 1000},
    {'Strategy': 'Strategy 4 (Cross)', 'Initial Capital': 100000, 'Final Value': s4_final, 'Total Return (%)': (s4_final - 100000) / 1000}
])

# Update final display
final_comparison_v2 = pd.concat([final_comparison, new_rows], ignore_index=True)
final_display_v2 = final_comparison_v2.copy()
final_display_v2['Final Value'] = final_display_v2['Final Value'].apply(lambda x: f"${x:,.2f}" if isinstance(x, (int, float)) else x)
final_display_v2['Total Return (%)'] = final_display_v2['Total Return (%)'].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)

print(f"--- Final Comparison including Strategy 3 and 4 for {TICKER_TO_FETCH} ---")
display(final_display_v2)
